import Style from "./emobilitaet.module.css"

export const Emobilitaet = () => {
    return (
        <div className={ Style.main_text }>
            Die Elektromobilität wird von der aktuellen Regierung und vielen Klimaexperten als elementar wichtigen Punkt für den Kampf gegen den Klimawandel angesehen, weshalb im ganzen Land ein Ausbau von Ladepunkten sowie eine Förderung der Autohersteller für E-Autos vorhanden ist. Besonders im niederbayerischen Landkreis Dingolfing-Landau wird die Elektromobilität als elementares Mittel für den Klimaschutz angesehen. Die Stadt Dingolfing sieht Elektroautos als wichtiges Element für den Schutz des Klimas: Zum einen senken Kraftfahrzeuge mit Elektroantrieb, die CO₂-Emissionen im Verkehr, die in Dingolfing insgesamt 35 % ausmachen und damit der zweitstärkste klimaschädliche Sektor hinter den privaten Haushalten mit 51 % sind, zum anderen kommt es zu einer Verringerung der Schadstoff- und Lärmemissionen. Zudem befindet man die Ladestationen als Fördermittel für den regionalen Einzelhandel, da Autofahrer eines Elektromobils während des Ladevorgangs „die vielfältigen Angebote rund um den Marienplatz wahrnehmen“   können, wie es auf der Webseite der Kreisstadt zu lesen ist. Auch die Stromart bei allen Ladestationen ist besonders klimafreundlich, da jeder Ladepunkt mit 100 % Ökostrom versorgt wird. Aufgrund der zahlreichen positiven Punkte soll die Anzahl der öffentlich zugänglichen Ladestationen in der Stadt ausgebreitet werden, um den Kauf eines solchen Autos attraktiver zu gestalten. Im Jahr 2021 kamen zu den Normalladestationen drei vom Bundesministerium für Verkehr und digitale Infrastruktur geförderte Schnellladestationen mit sechs DC (Schnellladung mit Gleichstrom) - und drei AC (Normalladung mit Wechselstrom) -Ladepunkten hinzu, wodurch es nun insgesamt 25 öffentliche Ladepunkte gibt, die durchaus von den Autofahrern benutzt werden.

            <img src='emobilitaet.png' alt='Ladestationen in Dingolfing' height='282px' width='605px'/>
 
            Öffentliche Ladestationen von Stadt und Stadtwerken in Dingolfing - Stadt Dingolfing
            Im Herbst vergangenen Jahres gab es rund elfmal so viel abgerechneten Strom an den Stationen der Stadtwerke Dingolfing GmbH im Vergleich zum Jahr 2020. Von dieser erhöhten Menge an Strom fallen circa 80 % auf die DC-Ladung an den Schnellladestationen zurück. Ab Anfang dieses Jahres wurden die bis dahin kostenfreien öffentlichen Lademöglichkeiten aufgrund einer immer größer werdenden Nachfrage kostenpflichtig. Laut der Stadt Dingolfing kann nur dadurch eine realistische Bedarfsermittlung für neue Ladepunkte ermöglicht werden. Eine spezielle Rolle kommt hierbei der BMW zu, die als Vorreiter in Sachen Elektromobilität gelten wollen. Monika Mayer, eine Vertreterin der BMW Group in Dingolfing, legt den Standpunkt des Unternehmens wie folgt dar: 
            Die BMW Group hat seit Jahren eine Vorreiterrolle bei der Transformation der Automobilindustrie hin zur E-Mobilität und stellt das Thema Elektrifizierung in den Fokus. Die BMW Group bekennt sich zu den Zielen des Pariser Klima-Abkommens und arbeitet konsequent an der Erreichung der CO2-Emissionsziele. Das Vorantreiben der E-Mobilität ist selbstverständlich ein maßgeblicher Baustein in Sachen Klimaschutz. Bis 2023 plant die BMW Group, ihre Fahrzeugpalette auf 25 elektrifizierte Fahrzeuge auszubauen, davon mehr als die Hälfte vollelektrisch. Im Jahr 2021 werden in Europa voraussichtlich bereits ein Viertel, der von der BMW Group abgesetzten Fahrzeuge elektrifiziert sein, 2025 bereits ein Drittel und 2030 die Hälfte. Zum Thema Ladestruktur für E-Fahrzeuge: Die BMW Group setzt seit 2013 weltweit Maßstäbe beim Aufbau der Ladeinfrastruktur. Das Unternehmen hat international 50 Projekte mit Partnern umgesetzt und bereits über 15.000 öffentliche Ladepunkte installiert. Der Ausbau der Lade-Infrastruktur an allen deutschen BMW Group Standorten in den letzten Jahren geht Hand in Hand mit der Erweiterung des BMW Group Modellprogramms um vollelektrische Premium-Automobile und Hybridfahrzeuge. Damit hat das Unternehmen einen entsprechend hohen Bedarf an E-Motoren und Batterien. Zentraler Dreh- und Angelpunkt in der Versorgung der Werke mit diesen E-Antriebskomponenten ist das BMW Group Werk in Dingolfing. Wir beliefern nicht nur das Fahrzeugwerk in Dingolfing, sondern auch einen Großteil der weltweiten Automobilwerke mit Batterien und E-Motoren. Der Standort in Niederbayern verfügt über eine langjährige Expertise im Bau von Komponenten für E-Fahrzeuge. Schon seit 2013 laufen hier im Serienbetrieb die Batterien für den BMW i3 vom Band. Seither werden Produkte und Prozesse kontinuierlich weiterentwickelt und optimiert. 
            Zusammenfassend lässt sich also sagen, dass BMW die Elektromobilität als Hauptfaktor in der Unternehmensstrategie sieht sowie eine Vorreiterrolle für andere Autohersteller innehaben will.
 
        </div>
    )
}