import React from 'react'
import Style from './gamedev.module.css'

export const Gamedev = () => {
  return (
    <div className={ Style.container }>
        <p className={ Style.quote }>„There is a definite argument to be made that videogames are becoming an art form put together by artists of different types.”</p>
         ~ John Romero
         <div className={Style.quoting_space} />
Videospiele sind eine Kunst, und für ihre Produktion werden viele Künstler völlig verschiedener Kunstarten benötigt, wie beispielsweise Artists, Musiker oder etwa die für Videospiele neue Art von Künstler – Game Designer. Auch Personen anderer Fachgebiete werden benötigt, hauptsächlich Programmierer, welche die von den Künstlern vorgegebenen Visionen auf dem Bildschirm ins Leben rufen. 
In Genau diese Aspekte wird der sogenannte Vorgang des Game Developements – kurz Game Dev – unterteilt: Game Design, Art, Programming und Music und Sound. Die letzteren drei sind dabei selbsterklärend. Artists kümmern sich um das visuelle Aussehen des Spiels und fertigen Sprites oder 3D-Modells an, Sound-Artists schaffen zu Situationen und Orten im Spiel passende Musik und Soundeffekte für nahezu jede Aktion des Spielers oder von NPCs und Programmierer setzen das Spiel mithilfe einer Programmiersprache um, sodass Menschen es am Computer genießen können. Nun bleibt nur noch der Begriff „Game Design“, welcher häufig fehlverstanden wird als ein Synonym für Art. Game Design ist jedoch etwas völlig anderes, es ist der Kern des Spiels, die Idee und das Konzept. Ein Game Designer legt die Idee für das ganze Spiel auf den Tisch, beantwortet grundlegendste Fragen wie etwa welches Genre es haben soll oder welche Zielgruppe es ansprechen soll. Er entwirft Ideen und Konzepte, meist mit dem Ziel ein für den Spieler spaßiges Erlebnis zu schaffen von Anfang bis zum Ende. Auch um winzige Details kümmert er sich, etwa wie schnell der Spieler laufen können soll und wie schnell er beschleunigt oder abbremst. Wichtig ist nur, dass alles, was der Game Designer macht, rein konzeptuell ist. Sein Ziel ist es nicht, Zeichnungen anzufertigen oder Dinge niederzuschreiben, auch wenn beides vermutlich von Nöten sein wird, um seinen Mitarbeitern seine Vorstellungen möglichst genau mitzuteilen.
Die meisten populären Videospiele werden von großen Entwicklerstudios geschaffen. Dabei wird jeder Aspekt des Game Devs von vielen kleineren Teams übernommen, welche sich jeweils nur um einen kleinen Aspekt des Spiels kümmern und diesen so lange ausarbeiten bis er perfekt funktioniert. Die Arbeit erfolgt hier nach striktem Zeitplan und Budget und kann durchaus etwas monoton sein, da man eben nur wenige Aufgaben, diese jedoch möglichst genau, erfüllen muss.
Anders ist dies als unabhängiger Entwickler – als sogenannter Indie Game Dev. Dies sind kleine Studios, bestehend aus nur wenigen oder sogar einer einzigen Person, welche ein Spiel produzieren. Dabei hat jede Person viele verschiedene Aufgaben und können sogar in verschiedene Felder übergreifen, beispielsweise kann eine Person sich sowohl um Game Design als auch die Programmierung kümmern. Die Arbeit sowie das Produkt hier ist selbstverständlich viel persönlicher, jedoch auch nicht ansatzweise so optimiert wie es bei einem großen Studio der Fall ist. Als Indie-Developer zu leben ist zwar deutlich Risikoreicher, die potentielle Belohnung dafür jedoch auch deutlich höher. Es ist auch kein unrealistischer Berufswunsch, schließlich werden Indie-Games in den letzten Jahren immer beliebter – eine Entwicklung, die kein Ende zu nehmen scheint. 
Nun da all dies geklärt ist, stellt sich nur noch die Frage: Wie erschaffe ich, zu Hause, mein eigenes Spiel, mein eigenes Kunstwerk? 
Der Prozess wird grundsätzlich in drei Abschnitte unterteilt, angefangen mit der Pre-Production. In dieser Phase denkt man sich zunächst das Grundkonzept aus. Dazu ist es ratsam, sich einige Inspiration von vielen anderen Spielen zu holen, sich zu überlegen welches Genre das Spiel haben soll und welche Gefühle es im Spieler auslösen soll. Ist die Idee gegeben, muss man auch Grundlegende Informationen auslegen: welches Publikum soll mein Spiel ansprechen? Wie finanziere ich es, falls nötig? Welche Game Engine benutze ich? Auch ein Zeitplan sollte, wie bei jedem großen Projekt, angefertigt werden. Ist all dies ausgelegt, so ist der nächste Schritt zunächst das Erstellen eines Game Design Documents, in welchem all diese  Informationen festgehalten werden, sowie das Spiel bereits vollständig auf dem Papier beschrieben, samt Idee, Handlung und wie der Spieler mit der Welt interagieren kann. Nun kann der Entwickler sich ans Implementieren machen. Doch noch bevor er anfängt an dem Endprodukt zu arbeiten, sollte ein Prototyp angefertigt werden, um den Spielspaß zu testen und die Idee verwerfen zu können, sollte sich herausstellen dass sie nicht die richtige ist, bevor Monate oder Jahre Arbeit an ihr verschwendet werden. 
Der nächste Schritt ist die Production. Hier wird das eigentliche Spiel erschaffen. Dazu baut man zunächst ein Grundgerüst. Bei einem Platformer wie Mario etwa bräuchte man als erstes einen Charakter, der auf einem Boden umherlaufen und von diesem abspringen kann. Und nun baut man das Spiel nach und nach in einem sich wiederholendem Prozess aus: Man nimmt das Konzept eines einzelnen Features, fertigt alle dazu nötigen Graphiken und Sounds an, implementiert es mit etwas Code im Spiel, testet dieses aus und ändert Einzelheiten wenn nötig. Hierbei wird es häufig passieren, dass neue Features mit alten interagieren und dazu die alten bearbeitet werden müssen, oft sogar völlig verworfen und neu implementiert, oder der Entwickler merkt dass bestimmte Graphiken nicht mehr ins Spiel passen und überarbeitet werden müssen, oder etwa Spieltester kritisieren einige Aspekte, welche auch wieder angepasst werden müssen. Man muss also ständig neue Dinge in das Spiel einbauen und zu alten zurückkehren, um diese zu verbessern, bis letztendlich ein fertiges Spiel entsteht. 
Doch damit ist es nicht fertig, denn nach Veröffentlichung folgt die Post-Production. Viele Spieler werden noch Fehler und Probleme entdecken, welche ausgebessert werden müssen und um langfristig eine Audienz zu halten muss man immer wieder neues Nachliefern, in Form von Updates, welche neue Features liefern.
Es ist wirklich nicht schwer ein Spiel zu erschaffen, ein wenig Vorerfahrung im Programmieren ist hilfreich, abgesehen davon ist alles, was man braucht, eine reine Übungssache, die jeder einfach versuchen kann. Ich selbst habe über ein Jahr mit einigen Freunden ein Spiel erschaffen, mit nichts weiter als grundlegenden Java-Kenntnissen, den Rest habe ich auf dieser Reise spontan herausgefunden und erlernt. 

    </div>
  )
}
